java_library(
    name = "hamcrest-all",
    exports = [
        "//external:jar/org/hamcrest/hamcrest-all"
    ],
    visibility = [
        "//visibility:public"
    ]
)



java_library(
    name = "hamcrest-core",
    exports = [
        "//external:jar/org/hamcrest/hamcrest-core"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


