java_test(
    name = "spliteratortest",
    srcs = glob(["*.java"]),
    test_class = "rocksdbtest.spliteratortest.RocksKeySpliteratorTest",
    deps = [
        "//base",
        "//dependencies/maven/artifacts/org/rocksdb:rocksdbjni",
        "//dependencies/maven/artifacts/org/hamcrest:hamcrest-all",
    ],
)