java_library(
    name = "graphdb",
    srcs = glob(["**/*.java"]),
    deps = [
        "//dependencies/maven/artifacts/org/rocksdb:rocksdbjni",
        "//dependencies/maven/artifacts/com/google/guava",
    ],
    visibility = ["//visibility:public"],
)