java_test(
    name = "test",
    srcs = [
        "CheckpointTest.java"
    ],
    test_class = "rocksdbtest.checkpoint.CheckpointTest",
    deps = [
        "//transaction",
        "//dependencies/maven/artifacts/org/rocksdb:rocksdbjni",
    ],
)
