java_binary(
    name = "paralleltest",
    srcs = glob(["*.java"]),
    main_class = "rocksdbtest.snapshot.TestSnapshotIsolation",
    deps = [
        "//dependencies/maven/artifacts/org/rocksdb:rocksdbjni",
    ],
)