
java_test(
    name = "snapshot-test",
    srcs = [
        "TestSnapshotIsolation.java"
    ],
    test_class = "rocksdbtest.snapshot.TestSnapshotIsolation",
    deps = [
        "//dependencies/maven/artifacts/org/rocksdb:rocksdbjni",
        "//dependencies/maven/artifacts/junit:junit",
    ],
)
