java_test(
    name = "test",
    srcs = [
        "RocksDatabase.java",
        "RocksTransaction.java",
        "TransactionTest.java"
    ],
    test_class = "rocksdbtest.transaction.TransactionTest",
    deps = [
        "//dependencies/maven/artifacts/org/rocksdb:rocksdbjni",
    ],
)
