java_library(
    name = "commons-math3",
    exports = [
        "//external:jar/org/apache/commons/commons-math3"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


